version: "3.9"
services:
  app:
    build: .
    image: app:latest
    volumes:
      - ./logs/:/logs/
    ports:
      - 8080:8080
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:7.17.14
    volumes:
      - ./resources/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
    environment:
      # - discovery.type=single-node
      # - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - elk

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.17.14
    volumes:
      - ./resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./resources/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.14
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    networks:
      - elk

networks:
  elk:
    driver: bridge
